version: '3.8'

services:
  clients:
    build: ./service-clients
    ports:
      - "3001:3001"
    env_file:
      - ./service-clients/.env
    depends_on:
      - rabbitmq
    networks:
      - kawa-net
    restart: unless-stopped

  commandes:
    build: ./APICommande
    ports:
      - "3000:3000"
    env_file:
      - ./APICommande/.env
    depends_on:
      - rabbitmq
    networks:
      - kawa-net
    restart: unless-stopped
  produits:
    build: ./APIProduit 
    ports:
      - "3003:3003"
    env_file:
      - ./APIProduit/.env
    depends_on:
      - rabbitmq
    networks:
      - kawa-net  
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - kawa-net
    restart: unless-stopped

networks:
  kawa-net:
