name: Build
on: push

jobs:

  sonarqube:
   name: SonarQube Scan
   runs-on: ubuntu-latest
   steps:
    - name: Checkout sorce code 
      uses: action/checkout@v2
      with:
       fetch-depth: 0
    - name: Setup Node.js
      uses: actions/srtup-node@v1
      with: 
       node-version: '18'
    - name: Install dependencies
      run: yarn install

    - name: Sonarqube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
